datapath:
  checkpoint_path: /Data1/hmd2/notebooks_th/Hmd_github/exps/MHA_LSTM_Semi
  external_data: /Data2/heart_sound_dataset
  test_data: /Data2/murmur/test
  train_data: /Data2/murmur/train
dataset:
  clean_noise: true
  frequency_high: 800
  hop_length: 0.02
  num_k: 5
  sampling_rate: 4000
  sequence_length: 6
  val_fold_num: 3
  window_length: 0.05
exp_params:
  const_max: 1
  ema_factor: 0.999
  learning_rate: 1e-5 # 5e-5
  mixup_alpha: 0.2
  mixup_beta: 0.2
  mixup_label_type: soft
  pos_weight: 4.0
  random_seed: 0
  strong_bs: 250   #  80
  total_epoch: 250
  training_patience: 10
  unlabel_bs: 400  #160
  use_mix_up: false
  val_bs: 120
virtual_settings:
  debug: false
  gpu_index: '0'
  num_workers: 8
  tuning: False
  verbose: 1
